kumuluzee:
  name: smartarticle-collections
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/CollectionsDS
      connection-url: jdbc:postgresql://159.122.187.161:32569/collection
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://159.122.187.161:31065
    discovery:
      etcd:
        hosts:http://159.122.187.161:31065
app-properties:
  collection-services:
    enabled: true
  collection-article-services:
    enabled: true