apiVersion: apps/v1
kind: Deployment
metadata:
  name: collection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collection
  template:
    metadata:
      labels:
        app: collection
    spec:
      containers:
      - image: ajugo/smartarticle-collections:0.6
        name: collection
        imagePullPolicy: "Always"
        env:
        - name: KUMULUZEE_DISCOVERY_CLUSTER
          value: gcloud
        - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_CONFIG_ETCD_HOSTS
          value: http://etcd:2379
        - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
          value: jdbc:postgresql://collection-db:5432/collection
        - name: KUMULUZEE_SERVER_BASEURL
          value: http://35.240.79.227:8083
        - name: KUMULUZEE_DATASOURCES0_USERNAME
          value: dbuser
        - name: KUMULUZEE_DATASOURCES0_PASSWORD
          value: postgres
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3

---

apiVersion: v1
kind: Service
metadata:
  name: collection
spec:
  type: LoadBalancer
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: collection